[package]
name = "op2"
description = "Next-Gen Optimism L2 Block Builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
publish = false

[dependencies]
rblib = { path = "../../" }


[dev-dependencies]
rblib = { path = "../../", features = ["test-utils"] }
