[package]
name = "flashblocks"
description = "Next-Gen Optimism L2 Block Builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
publish = false

[features]
default = ["jemalloc"]
jemalloc = ["rblib/jemalloc"]

[dependencies]
rblib = { path = "../../", features = ["optimism"] }

futures = "0.3"
tokio = "1.46"
tokio-tungstenite = "0.27"
parking_lot = "0.12"
eyre = "0.6"
moka = "0.12"
tracing = "0.1"
clap = { version = "4.4", features = ["derive", "env", "string"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.33"

url = "2.5.2"
rand = "0.9"
derive_more = "2.0"
shellexpand = "3.1"
humantime = "2.2"
atomic-time = "0.1"

secp256k1 = "0.30"
jsonrpsee = "0.25.1"

alloy-json-rpc = "1.0.18"
alloy-serde = "1.0.23"

# reth dependencies
reth-network-peers = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-db-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-node-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-optimism-rpc = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }

[dev-dependencies]
rblib = { path = "../../", features = ["optimism", "test-utils"] }

dashmap = "6.1"
orx-concurrent-vec = "3.7.0"
itertools = "0.14"

[lints]
workspace = true
