[package]
name = "flashblocks"
description = "Next-Gen Optimism L2 Block Builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
publish = false

[features]
default = ["jemalloc"]
jemalloc = ["rblib/jemalloc"]

[dependencies]
rblib = { path = "../../" }

tokio = { version = "1.46" }
eyre = { version = "0.6" }
clap = { version = "4.4", features = ["derive", "env", "string"] }
url = "2.5.2"
rand = "0.9"
serde_json = "1.0"
serde_yaml = "0.9"
secp256k1 = "0.30"
shellexpand = "3.1"
jsonrpsee = "0.25.1"
alloy-json-rpc = "1.0.18"

# reth dependencies
reth-network-peers = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }

[dev-dependencies]
rblib = { path = "../../", features = ["test-utils"] }
