name: Sanity Check
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  lint_and_test:
    runs-on: warp-ubuntu-latest-x64-32x
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - uses: actions/checkout@v2
      - name: Set up Rust Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: false
          components: rustfmt

      - name: Run Rustfmt with nightly
        run: cargo +nightly fmt --all -- --check

      - name: Run Clippy with stable
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run Tests with stable
        run: cargo test --all-targets --all-features